"""added created at col

Revision ID: 420f4a15a274
Revises: ffd5da6b2742
Create Date: 2024-03-15 17:46:05.427089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420f4a15a274'
down_revision: Union[str, None] = 'ffd5da6b2742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge', 'created_at')
    # ### end Alembic commands ###
