"""update condition edge relation

Revision ID: b0d5e10cb082
Revises: 420f4a15a274
Create Date: 2024-03-17 13:53:02.888166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d5e10cb082'
down_revision: Union[str, None] = '420f4a15a274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('condition_no_edge_id_fkey', 'condition', type_='foreignkey')
    op.drop_constraint('condition_yes_edge_id_fkey', 'condition', type_='foreignkey')
    op.create_foreign_key(None, 'condition', 'edge', ['no_edge_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'condition', 'edge', ['yes_edge_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'condition', type_='foreignkey')
    op.drop_constraint(None, 'condition', type_='foreignkey')
    op.create_foreign_key('condition_yes_edge_id_fkey', 'condition', 'edge', ['yes_edge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('condition_no_edge_id_fkey', 'condition', 'edge', ['no_edge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
