"""init

Revision ID: ffd5da6b2742
Revises: 
Create Date: 2024-03-15 12:56:55.948346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd5da6b2742'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_id'), 'workflow', ['id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('start', 'message', 'condition', 'end', name='nodetypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_node_id != target_node_id', name='check_source_node_not_equal_target_node'),
    sa.ForeignKeyConstraint(['source_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', name='unq_source_node_target_node')
    )
    op.create_index(op.f('ix_edge_id'), 'edge', ['id'], unique=False)
    op.create_table('message',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'opened', name='messagestatusenum'), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('condition',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(length=100), nullable=False),
    sa.Column('yes_edge_id', sa.Integer(), nullable=True),
    sa.Column('no_edge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['no_edge_id'], ['edge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yes_edge_id'], ['edge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition')
    op.drop_table('message')
    op.drop_index(op.f('ix_edge_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_workflow_id'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###
